#Site Settings
title: Marc Dekeyser
author: Marc Dekeyser
description: Dare to be authentic, passionate, and curious
theme: minima

# Optional features
show_related_posts: True
show_post_footers: True
show_subscribe_cta: True
show_social_icons: True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: 
stackoverflow_id:
twitter_username: 
linkedin_username: 

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"
